
version: '3'

services:
  payment:

    image: edfrancys/vejartespayment:v2

    deploy:
      mode: replicated
      #placement:
      #  constraints:
      #    - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        # App-labbels
        - "traefik.enable=true"
        - "traefik.docker.network=proxy-traefik"
        - "traefik.http.routers.payment.rule=Host(`cvdigital.net.br`)"
        - "traefik.http.routers.payment.service=payment"
        - "traefik.http.routers.payment.tls.certresolver=default"
        - "traefik.http.routers.payment.entrypoints=web,websecure"
        - "traefik.http.services.payment.loadbalancer.server.port=3000"


    networks:
      - proxy-traefik

networks:
  proxy-traefik:
    external: true
