
version: '3'

services:
  ecorun:

    image: edfrancys/ecorun

    deploy:
      mode: replicated
      #placement:
      #  constraints:
      #    - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        # App-labbels
        - "traefik.enable=true"
        - "traefik.docker.network=proxy-traefik"
        - "traefik.http.routers.ecorun.rule=Host(`ecorun.cvdigital.net.br`)"
        - "traefik.http.routers.ecorun.service=ecorun"
        - "traefik.http.routers.ecorun.tls.certresolver=default"
        - "traefik.http.routers.ecorun.entrypoints=web,websecure"
        - "traefik.http.services.ecorun.loadbalancer.server.port=3000"


    networks:
      - proxy-traefik

networks:
  proxy-traefik:
    external: true
